Loading required package: parallel
Error in file(file, "r") : cannot open the connection
Calls: scan -> file
In addition: Warning message:
In file(file, "r") :
  cannot open file '/hpf/largeprojects/agoldenb/ben/Projects/SNF/NM_2015/Scripts/06_Cluster_Sizes/evaluate_original_similarity/../cluster_complete_data/Results/Labels/3_1_3.txt': No such file or directory
Execution halted
